from src.recommender_core.recommender_algorithms\
    .user_based_algorithms.user_keywords_recommendation import UserBasedMethods

user_based_recommendation = UserBasedMethods()
user_based_recommendation.load_best_rated_by_others_in_user_categories(371)
