from src.recommender_core.recommender_algorithms.user_based_algorithms.user_based_recommendation import UserBasedRecommendation

user_based_recommendation = UserBasedRecommendation()
user_based_recommendation.load_recommended_posts_for_user(371)