name: Tests

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    env:
      DB_RECOMMENDER_HOST: ${{secrets.DB_RECOMMENDER_HOST}}
      DB_RECOMMENDER_NAME: ${{secrets.DB_RECOMMENDER_NAME}}
      DB_RECOMMENDER_PASSWORD: ${{secrets.DB_RECOMMENDER_PASSWORD}}
      DB_RECOMMENDER_USER: ${{secrets.DB_RECOMMENDER_USER}}
      REDIS_PASSWORD: ${{secrets.REDIS_PASSWORD}}
      DB_RECOMMENDER_TESTING_USER: ${{secrets.DB_RECOMMENDER_TESTING_USER}}
      DB_RECOMMENDER_TESTING_HOST: ${{secrets.DB_RECOMMENDER_TESTING_HOST}}
      DB_RECOMMENDER_TESTING_NAME: ${{secrets.DB_RECOMMENDER_TESTING_NAME}}
      DB_RECOMMENDER_TESTING_PASSWORD: ${{secrets.DB_RECOMMENDER_TESTING_PASSWORD}}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.8', '3.9', '3.10']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Create DB
        run: |
          sudo apt update --yes
          sudo apt install postgresql --yes
          sudo service postgresql start
          sudo -u postgres createdb ${{secrets.DB_RECOMMENDER_TESTING_HOST}}
          sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'braf';"
      - name: Importing .sql
        run: |
          export PGPASSWORD='braf'
          for i in database/db_backups/core_testing_db_dumps/*.sql; do psql -h ${{secrets.DB_RECOMMENDER_TESTING_HOST}} -d ${{secrets.DB_RECOMMENDER_TESTING_NAME}} -U ${{secrets.DB_RECOMMENDER_TESTING_USER}} -p 5432 -a -w -f $i; done
      - name: Install dependencies
        run: |
          sudo -H pip install --upgrade pip tox virtualenv
          pip install tox tox-gh-actions
      - name: Test with tox
        run: tox
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"
      - name: Run Gitleaks
        id: gitleaks
        uses: DariuszPorowski/github-action-gitleaks@v2
        with:
          config: "MyGitleaksConfigs/MyGitleaksConfig.toml"

      - name: Upload Gitleaks JSON report to artifacts
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: gitleaks
          path: tests/logs/gitactions