name: Tests

on:
  - push
  - pull_request

jobs:
  test:
    environment: moje-clanky-api
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11.0-beta.3']
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions

        ports:
          - 5433:5432

        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      DB_RECOMMENDER_HOST: ${{ secrets.DB_RECOMMENDER_HOST }}
      DB_RECOMMENDER_NAME: ${{ secrets.DB_RECOMMENDER_NAME }}
      DB_RECOMMENDER_PASSWORD: ${{ secrets.DB_RECOMMENDER_PASSWORD }}
      DB_RECOMMENDER_USER: ${{ secrets.DB_RECOMMENDER_USER }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: 'Install dependencies'
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Test with tox
      run: tox